// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func focusScript() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_focusScript_1b52`,
		Function: `function __templ_focusScript_1b52(){var start = new Date().getTime();

  let x = setInterval(() => {
    var elapsed = new Date().getTime() - start;

    var hours = Math.floor((elapsed % (1000 * 60 * 60 * 24)) / (60 * 60 * 1000));

    var minutes = Math.floor((elapsed % (1000 * 60 * 60)) / (60 * 1000));

    var seconds = Math.floor((elapsed % (1000 * 60)) / 1000);

    var f = ` + "`" + `${padZeroes(hours)}:${padZeroes(minutes)}:${padZeroes(seconds)}` + "`" + `;
    document.getElementById("counter").innerHTML = f;
    document.getElementById("title").innerHTML = f + " | GoMato";
    document.getElementById("pause-button").value = elapsed;
    totalElapsed = elapsed;
  }, 1000);

  document.getElementById("clock").addEventListener('htmx:beforeSend', function(evt) {
    clear()
  });

  function clear() {
    console.log("clearing")
    clearInterval(x)
  }

  function padZeroes(num) {
    return (num < 10 ? "0" : "") + num;
  }}`,
		Call:       templ.SafeScript(`__templ_focusScript_1b52`),
		CallInline: templ.SafeScriptInline(`__templ_focusScript_1b52`),
	}
}

func Focus() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<article id=\"clock\"><h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := `Focus Mode`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h1><b id=\"counter\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var3 := `00:00:00`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</b> <button onclick=\"clear()\" id=\"pause-button\" hx-post=\"/pause\" value=\"0\" name=\"time\" hx-swap=\"outerHTML\" hx-target=\"#clock\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var4 := `Start Pause`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = focusScript().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</article>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
