// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func pauseScript(startTime int) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_pauseScript_21fe`,
		Function: `function __templ_pauseScript_21fe(startTime){var start = new Date().getTime() + startTime;
  document.getElementById("counter").innerHTML = toTimeString(startTime);

  let y = setInterval(() => {
    var elapsed = start - new Date().getTime();
    let f = toTimeString(elapsed);
    document.getElementById("counter").innerHTML = f;
  }, 1000);

  function padZeroes(num) {
    return (num < 10 ? "0" : "") + num;
  }

  function toTimeString(ms) {
    if (ms <= 0) return "00:00:00"

    var hours = Math.floor((ms % (1000 * 60 * 60 * 24)) / (60 * 60 * 1000));
    var minutes = Math.floor((ms % (1000 * 60 * 60)) / (60 * 1000));
    var seconds = Math.floor((ms % (1000 * 60)) / 1000);

    return ` + "`" + `${padZeroes(hours)}:${padZeroes(minutes)}:${padZeroes(seconds)}` + "`" + `;
  }

  document.getElementById("clock").addEventListener('htmx:beforeSend', function(evt) {
    clear()
  });

  function clear() {
    clearInterval(y)
  }}`,
		Call:       templ.SafeScript(`__templ_pauseScript_21fe`, startTime),
		CallInline: templ.SafeScriptInline(`__templ_pauseScript_21fe`, startTime),
	}
}

func Pause(startTime int) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<article id=\"clock\"><h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := `On Break...`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h1><b id=\"counter\"></b> <button id=\"play-button\" hx-get=\"/focus\" hx-swap=\"outerHTML\" hx-target=\"#clock\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var3 := `Start Focus`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = pauseScript(startTime).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</article>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
